### PR TITLE
ci: fix shellcheck in test-go

### PR DESCRIPTION
**Pull request by agarwal-mudit**
Fixed shellcheck in test-go script

Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
Signed-off-by: Niels de Vos <ndevos@redhat.com>
(cherry picked from commit fdbd4877413bc96305be87bab9e80f699e9f95dc)

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
@Madhu-1

**Comment by Madhu-1** [comment]
>https://github.com/openshift/ceph-csi/blob/release-4.6/OWNERS

OWNERS page is still missing. Merging this one for now.

**Pull request merged**
