### PR TITLE
ci: add OWNERS file to the repo

### PR DESCRIPTION
**Pull request by agarwal-mudit**
Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

### CODE REVIEW

**Comment by agarwal-mudit** [comment]
@Madhu-1  @nixpanic This needs manual merge as we still don't have OWNERS file
I will send separate PRs for each branch once this is merged.

**Comment by Madhu-1** [comment]
Do we need it in upstream and backport it to downstream?

**Comment by agarwal-mudit** [comment]
> Do we need it in upstream and backport it to downstream?

You guys decide, if you need in upstream then I can send the PR there. Or if you think that's a better process then let me know.

**Comment by Madhu-1** [comment]
@agarwal-mudit @humblec started one long back https://github.com/ceph/ceph-csi/pull/1150 but got closed by bot due to inactivity.

**Review by nixpanic — APPROVED** [review]

**Comment by nixpanic** [comment]
> @agarwal-mudit @humblec started one long back [ceph#1150](https://github.com/ceph/ceph-csi/pull/1150) but got closed by bot due to inactivity.

Well, we do not use the file in upstream, only in this fork. So I would object to including it in upstream (what would we do when some other organization has their own downstream fork?).

**Comment by nixpanic** [comment]
I think we might need this file for each branch in the repository? We can check with PR #22 and see if someone can approve that.

**Comment by agarwal-mudit** [comment]
I will cherry-pick

**Pull request merged**
