### PR TITLE
Syncing ceph-csi/devel with openshfit/release-4.8

### PR DESCRIPTION
**Pull request by agarwal-mudit**
# Describe what this PR does #

Provide some context for the reviewer

## Is there anything that requires special attention ##

Do you have any questions?

Is the change backward compatible?

Are there concerns around backward compatibility?

Provide any external context for the change, if any.

For example:

* Kubernetes links that explain why the change is required
* CSI spec related changes/catch-up that necessitates this patch
* golang related practices that necessitates this change

## Related issues ##

Mention any github issues relevant to this PR. Adding below line
will help to auto close the issue once the PR is merged.

Fixes: #issue_number

## Future concerns ##

List items that are not part of the PR and do not impact it's
functionality, but are work items that can be taken up subsequently.

---

<details>
<summary>Show available bot commands</summary>

These commands are normally not required, but in case of issues, leave any of
the following bot commands in an otherwise empty comment in this PR:

- `/retest ci/centos/<job-name>`: retest the `<job-name>` after unrelated
  failure (please report the failure too!)
- `/retest all`: run this in case the CentOS CI failed to start/report any test
  progress or results

</details>

### CODE REVIEW

**Review by nixpanic — CHANGES_REQUESTED** [review]
This first needs to be done for the master branch, and then it can be backported to release-4.8.

**Comment by humblec** [comment]
> This first needs to be done for the master branch, and then it can be backported to release-4.8.

@nixpanic the devel branch is already synced .

**Comment by nixpanic** [comment]
/hold

We do not use a `devel` branch in this repository. All syncing needs to be done in the `master` branch, with a PR similar to this one. We can then have the PR merged, and `/cherry-pick release-4.8` it into the release branch.

**Comment by agarwal-mudit** [comment]
We don't need to cherry-pick till feature freeze

**Pull request closed without merging**
