### PR TITLE
bug 1936388: RBD PVC with thick provisioning is failing

### PR DESCRIPTION
**Pull request by nixpanic**
This is a rebase on top of the upstream ceph-ceph/devel branch, which fixes several issues with thick-provisioning.

### CODE REVIEW

**Comment by nixpanic** [comment]
The build logs are not immediately visible, but after a little looking, I found them here: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ceph-csi/22/pull-ci-openshift-ceph-csi-release-4.8-static-checks/1369957481144389632/artifacts/test/build-log.txt

**Review by agarwal-mudit — APPROVED** [review]

**Comment by nixpanic** [comment]
/test tide

It seems the `/override` picked up the new `OWNERS`, maybe **tide** can try again and see the approval from Mudit now?

**Comment by nixpanic** [comment]
/approve

Not sure this helps, but the `/test tide` did not.

**Comment by agarwal-mudit** [comment]
> /test tide
> 
> It seems the `/override` picked up the new `OWNERS`, maybe **tide** can try again and see the approval from Mudit now?

But it still has invalid-bug tag

**Comment by nixpanic** [comment]
/remove-label bugzilla/invalid-bug

This should get addressed with openshift/release#16722 at one point.

**Comment by nixpanic** [comment]
This has been a nice test, will abort this change and have it done in the master branch instead.

**Pull request closed without merging**
